/**
 * Ollama response parsing, against recorded responses.
 *
 * The fixtures are the shapes Ollama actually returns, trimmed of model names
 * that would date the file. They are the contract: if `/api/tags` or
 * `/api/show` changes shape, these fail here rather than in a user's empty
 * Models tab.
 *
 * The malformed cases matter as much as the happy path. A response that cannot be
 * read has to raise rather than parse into an empty list, because "Ollama is
 * running with nothing installed" and "Ollama sent something unexpected" are
 * different things and the UI gives the user different advice for each.
 */

import { describe, expect, it } from "vitest";

import {
  formatBytes,
  ollamaRootFrom,
  parsePullLine,
  parseShow,
  parseTags,
  toModelInfo,
  capabilitiesFromShow,
  OllamaParseError,
  type OllamaModelSummary,
} from "./catalog.js";

/** Recorded `GET /api/tags`, two installed models plus an embedding model. */
const TAGS_FIXTURE = {
  models: [
    {
      name: "qwen3-coder:30b",
      model: "qwen3-coder:30b",
      modified_at: "2026-02-11T09:14:02.117894Z",
      size: 18_591_346_432,
      digest: "sha256:1f2e3d4c5b6a7988aabbccddeeff00112233445566778899aabbccddeeff00",
      details: {
        parent_model: "",
        format: "gguf",
        family: "qwen3",
        families: ["qwen3"],
        parameter_size: "30.8B",
        quantization_level: "Q4_K_M",
      },
    },
    {
      name: "gemma3:4b",
      model: "gemma3:4b",
      modified_at: "2026-01-30T21:03:44.901233Z",
      size: 3_301_373_248,
      digest: "sha256:aa11bb22cc33dd44ee55ff6677889900aabbccddeeff00112233445566778899",
      details: {
        parent_model: "",
        format: "gguf",
        family: "gemma3",
        families: ["gemma3"],
        parameter_size: "4.3B",
        quantization_level: "Q8_0",
      },
    },
    {
      name: "nomic-embed-text:latest",
      model: "nomic-embed-text:latest",
      modified_at: "2025-12-02T08:00:00.000000Z",
      size: 274_302_450,
      digest: "sha256:99887766554433221100ffeeddccbbaa00998877665544332211ffeeddccbbaa",
      details: {
        parent_model: "",
        format: "gguf",
        family: "nomic-bert",
        families: ["nomic-bert"],
        parameter_size: "137M",
        quantization_level: "F16",
      },
    },
  ],
} as const;

/** Recorded `POST /api/show` for a tool- and vision-capable model. */
const SHOW_FIXTURE = {
  license: "apache-2.0",
  modelfile: "# Modelfile generated by `ollama show`\nFROM qwen3-coder:30b",
  parameters: "stop  \"<|im_end|>\"\ntemperature 0.7",
  template: "{{ .System }} {{ .Prompt }}",
  details: {
    parent_model: "",
    format: "gguf",
    family: "qwen3",
    families: ["qwen3"],
    parameter_size: "30.8B",
    quantization_level: "Q4_K_M",
  },
  model_info: {
    "general.architecture": "qwen3",
    "general.parameter_count": 30_800_000_000,
    "qwen3.context_length": 262_144,
    "qwen3.embedding_length": 4_096,
    "qwen3.block_count": 48,
  },
  capabilities: ["completion", "tools", "thinking"],
  modified_at: "2026-02-11T09:14:02.117894Z",
} as const;

/** Recorded `POST /api/show` for a vision model. */
const SHOW_VISION_FIXTURE = {
  details: { family: "gemma3", parameter_size: "4.3B", quantization_level: "Q8_0" },
  model_info: {
    "general.architecture": "gemma3",
    "gemma3.context_length": 131_072,
  },
  capabilities: ["completion", "vision"],
} as const;

/** An Ollama older than the `capabilities` field. */
const SHOW_LEGACY_FIXTURE = {
  details: { family: "llama", parameter_size: "7B", quantization_level: "Q4_0" },
  model_info: {
    "general.architecture": "llama",
    "llama.context_length": 4_096,
  },
} as const;

describe("GET /api/tags", () => {
  it("reads every installed model with its size and details", () => {
    const models = parseTags(TAGS_FIXTURE);
    expect(models).toHaveLength(3);
    expect(models[0]).toEqual({
      id: "qwen3-coder:30b",
      size: 18_591_346_432,
      parameterSize: "30.8B",
      quantization: "Q4_K_M",
      family: "qwen3",
      modifiedAt: "2026-02-11T09:14:02.117894Z",
    });
  });

  it("keeps the tag, because two tags of one model are two models", () => {
    const models = parseTags(TAGS_FIXTURE);
    // Dropping the tag would make a request ambiguous once `latest` and a pinned
    // version are both installed.
    expect(models.map((model) => model.id)).toEqual([
      "qwen3-coder:30b",
      "gemma3:4b",
      "nomic-embed-text:latest",
    ]);
  });

  it("falls back to the `model` field when `name` is absent", () => {
    const models = parseTags({ models: [{ model: "legacy-naming:7b", size: 42 }] });
    expect(models[0]?.id).toBe("legacy-naming:7b");
    // Absent details must not become empty strings, which would render as blanks.
    expect(models[0]?.parameterSize).toBeUndefined();
    expect(models[0]?.size).toBe(42);
  });

  it("treats an empty list as a valid answer, not a parse failure", () => {
    // A fresh Ollama has nothing installed, and the UI has a pull prompt for
    // exactly that state. Throwing here would show a parse error instead.
    expect(parseTags({ models: [] })).toEqual([]);
  });

  it("rejects a body that is not the documented shape", () => {
    expect(() => parseTags({ objects: [] })).toThrow(OllamaParseError);
    expect(() => parseTags({ models: {} })).toThrow(OllamaParseError);
    expect(() => parseTags(null)).toThrow(OllamaParseError);
    expect(() => parseTags("not json")).toThrow(OllamaParseError);
    expect(() => parseTags([])).toThrow(OllamaParseError);
  });

  it("rejects an entry with no name at all", () => {
    expect(() => parseTags({ models: [{ size: 1 }] })).toThrow(/no name/i);
  });
});

describe("POST /api/show", () => {
  it("reads the context length keyed by architecture", () => {
    expect(parseShow(SHOW_FIXTURE).contextWindow).toBe(262_144);
    expect(parseShow(SHOW_VISION_FIXTURE).contextWindow).toBe(131_072);
  });

  it("reads capabilities", () => {
    const detail = parseShow(SHOW_FIXTURE);
    expect(detail.capabilities).toEqual(["completion", "tools", "thinking"]);
    expect(capabilitiesFromShow(detail).tools).toBe(true);
    expect(capabilitiesFromShow(detail).vision).toBe(false);
  });

  it("treats Ollama's `thinking` as reasoning", () => {
    expect(capabilitiesFromShow(parseShow(SHOW_FIXTURE)).reasoning).toBe(true);
  });

  it("marks vision only when Ollama says so", () => {
    const detail = parseShow(SHOW_VISION_FIXTURE);
    expect(capabilitiesFromShow(detail).vision).toBe(true);
    expect(capabilitiesFromShow(detail).tools).toBe(false);
  });

  it("claims nothing on an Ollama too old to report capabilities", () => {
    // The failure this prevents: showing a `tools` badge on a model that cannot
    // call tools, and then having the agent fail mid-run instead.
    const detail = parseShow(SHOW_LEGACY_FIXTURE);
    expect(detail.capabilities).toEqual([]);
    const capabilities = capabilitiesFromShow(detail);
    expect(capabilities.tools).toBe(false);
    expect(capabilities.vision).toBe(false);
    // The context length is still there, because that field is not new.
    expect(capabilities.contextWindow).toBe(4_096);
  });

  it("still reads a context length when capabilities are absent", () => {
    expect(parseShow(SHOW_LEGACY_FIXTURE).contextWindow).toBe(4_096);
  });

  it("does not hardcode architectures", () => {
    // A family released after this test was written must still report its window.
    const detail = parseShow({
      model_info: { "some-future-arch.context_length": 999_999 },
      capabilities: ["completion"],
    });
    expect(detail.contextWindow).toBe(999_999);
  });

  it("reports no context window when none is published", () => {
    const detail = parseShow({ capabilities: ["completion"], model_info: {} });
    expect(detail.contextWindow).toBeUndefined();
    expect(capabilitiesFromShow(detail).contextWindow).toBeUndefined();
  });

  it("rejects a non-object body", () => {
    expect(() => parseShow("nope")).toThrow(OllamaParseError);
    expect(() => parseShow(null)).toThrow(OllamaParseError);
  });
});

describe("toModelInfo", () => {
  const summary: OllamaModelSummary = parseTags(TAGS_FIXTURE)[0]!;

  it("carries the id, size-derived description and capabilities across", () => {
    const model = toModelInfo(summary, parseShow(SHOW_FIXTURE));
    expect(model.id).toBe("qwen3-coder:30b");
    expect(model.name).toBe("qwen3-coder:30b");
    expect(model.wireFormat).toBe("openai-chat");
    expect(model.capabilities.contextWindow).toBe(262_144);
    expect(model.capabilities.tools).toBe(true);
    expect(model.description).toBe("qwen3 · 30.8B · Q4_K_M");
  });

  it("invents no capabilities when details could not be fetched", () => {
    // Reachable-but-unenriched is a normal state: `/api/show` can fail for one
    // model while the rest of the list is fine.
    const model = toModelInfo(summary, undefined);
    expect(model.capabilities.tools).toBe(false);
    expect(model.capabilities.contextWindow).toBeUndefined();
    expect(model.id).toBe(summary.id);
  });

  it("reports no price, so freeness is decided by the provider", () => {
    expect(toModelInfo(summary, undefined).cost).toBeUndefined();
  });
});

describe("POST /api/pull progress", () => {
  it("reads a layer download with byte counts", () => {
    const progress = parsePullLine(
      '{"status":"pulling aabbccdd","digest":"sha256:aabb","total":2019393189,"completed":1048576}',
    );
    expect(progress).toEqual({
      status: "pulling aabbccdd",
      completed: 1_048_576,
      total: 2_019_393_189,
      done: false,
    });
  });

  it("marks success as done", () => {
    expect(parsePullLine('{"status":"success"}')).toEqual({ status: "success", done: true });
  });

  it("reads a status line with no counts", () => {
    expect(parsePullLine('{"status":"verifying sha256 digest"}')).toEqual({
      status: "verifying sha256 digest",
      done: false,
    });
  });

  it("skips a line it cannot read rather than failing the download", () => {
    // A pull is minutes and gigabytes; one bad line must not throw it away.
    expect(parsePullLine("not json")).toBeNull();
    expect(parsePullLine("")).toBeNull();
    expect(parsePullLine("[1,2,3]")).toBeNull();
    expect(parsePullLine('{"error":"pull model manifest: file does not exist"}')).toBeNull();
  });
});

describe("base URL handling", () => {
  it("keeps the native root as-is", () => {
    expect(ollamaRootFrom("http://localhost:11434")).toBe("http://localhost:11434");
  });

  it("strips the OpenAI-compatible suffix the registry stores", () => {
    // The registry points completions at `/v1`; `/api/tags` is at the root, and
    // the user should only ever have to edit the URL in one place.
    expect(ollamaRootFrom("http://localhost:11434/v1")).toBe("http://localhost:11434");
    expect(ollamaRootFrom("http://127.0.0.1:11434/v1/")).toBe("http://127.0.0.1:11434");
  });

  it("defaults when unset", () => {
    expect(ollamaRootFrom("")).toBe("http://localhost:11434");
    expect(ollamaRootFrom(null)).toBe("http://localhost:11434");
    expect(ollamaRootFrom(undefined)).toBe("http://localhost:11434");
  });

  it("keeps a custom host and port", () => {
    expect(ollamaRootFrom("http://192.168.1.50:22434/v1")).toBe("http://192.168.1.50:22434");
  });
});

describe("formatBytes", () => {
  it("scales to a readable unit", () => {
    expect(formatBytes(512)).toBe("512 B");
    expect(formatBytes(18_591_346_432)).toBe("17 GB");
    expect(formatBytes(3_301_373_248)).toBe("3.1 GB");
    expect(formatBytes(274_302_450)).toBe("262 MB");
  });

  it("returns null for a size Ollama did not report", () => {
    expect(formatBytes(undefined)).toBeNull();
    expect(formatBytes(-1)).toBeNull();
  });
});

describe("capabilities, as Ollama actually reports them", () => {
  it("does not call a plain completion model reasoning-capable", () => {
    // "completion" is in every completion model's list, so reading reasoning
    // from it would badge the entire library.
    const caps = capabilitiesFromShow(parseShow(SHOW_VISION_FIXTURE));
    expect(caps.reasoning).toBe(false);
    expect(caps.vision).toBe(true);
  });

  it("reads reasoning from thinking", () => {
    expect(capabilitiesFromShow(parseShow(SHOW_FIXTURE)).reasoning).toBe(true);
  });

  it("treats a response with no capabilities field as no capabilities", () => {
    const caps = capabilitiesFromShow(parseShow(SHOW_LEGACY_FIXTURE));
    expect(caps.reasoning).toBe(false);
    expect(caps.tools).toBe(false);
    expect(caps.vision).toBe(false);
  });

  it("reads the context window from the architecture-specific key", () => {
    // "qwen3.context_length", not a top-level field.
    expect(parseShow(SHOW_FIXTURE).contextWindow).toBe(262_144);
  });

  it("omits the context window when Ollama reports none", () => {
    const caps = capabilitiesFromShow(parseShow({ capabilities: ["completion"] }));
    expect(caps.contextWindow).toBeUndefined();
  });
});
